require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CidadeempresasController do

  # This should return the minimal set of attributes required to create a valid
  # Cidadeempresa. As you add validations to Cidadeempresa, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "nomecidade" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CidadeempresasController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all cidadeempresas as @cidadeempresas" do
      cidadeempresa = Cidadeempresa.create! valid_attributes
      get :index, {}, valid_session
      assigns(:cidadeempresas).should eq([cidadeempresa])
    end
  end

  describe "GET show" do
    it "assigns the requested cidadeempresa as @cidadeempresa" do
      cidadeempresa = Cidadeempresa.create! valid_attributes
      get :show, {:id => cidadeempresa.to_param}, valid_session
      assigns(:cidadeempresa).should eq(cidadeempresa)
    end
  end

  describe "GET new" do
    it "assigns a new cidadeempresa as @cidadeempresa" do
      get :new, {}, valid_session
      assigns(:cidadeempresa).should be_a_new(Cidadeempresa)
    end
  end

  describe "GET edit" do
    it "assigns the requested cidadeempresa as @cidadeempresa" do
      cidadeempresa = Cidadeempresa.create! valid_attributes
      get :edit, {:id => cidadeempresa.to_param}, valid_session
      assigns(:cidadeempresa).should eq(cidadeempresa)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Cidadeempresa" do
        expect {
          post :create, {:cidadeempresa => valid_attributes}, valid_session
        }.to change(Cidadeempresa, :count).by(1)
      end

      it "assigns a newly created cidadeempresa as @cidadeempresa" do
        post :create, {:cidadeempresa => valid_attributes}, valid_session
        assigns(:cidadeempresa).should be_a(Cidadeempresa)
        assigns(:cidadeempresa).should be_persisted
      end

      it "redirects to the created cidadeempresa" do
        post :create, {:cidadeempresa => valid_attributes}, valid_session
        response.should redirect_to(Cidadeempresa.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved cidadeempresa as @cidadeempresa" do
        # Trigger the behavior that occurs when invalid params are submitted
        Cidadeempresa.any_instance.stub(:save).and_return(false)
        post :create, {:cidadeempresa => { "nomecidade" => "invalid value" }}, valid_session
        assigns(:cidadeempresa).should be_a_new(Cidadeempresa)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Cidadeempresa.any_instance.stub(:save).and_return(false)
        post :create, {:cidadeempresa => { "nomecidade" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested cidadeempresa" do
        cidadeempresa = Cidadeempresa.create! valid_attributes
        # Assuming there are no other cidadeempresas in the database, this
        # specifies that the Cidadeempresa created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Cidadeempresa.any_instance.should_receive(:update_attributes).with({ "nomecidade" => "MyString" })
        put :update, {:id => cidadeempresa.to_param, :cidadeempresa => { "nomecidade" => "MyString" }}, valid_session
      end

      it "assigns the requested cidadeempresa as @cidadeempresa" do
        cidadeempresa = Cidadeempresa.create! valid_attributes
        put :update, {:id => cidadeempresa.to_param, :cidadeempresa => valid_attributes}, valid_session
        assigns(:cidadeempresa).should eq(cidadeempresa)
      end

      it "redirects to the cidadeempresa" do
        cidadeempresa = Cidadeempresa.create! valid_attributes
        put :update, {:id => cidadeempresa.to_param, :cidadeempresa => valid_attributes}, valid_session
        response.should redirect_to(cidadeempresa)
      end
    end

    describe "with invalid params" do
      it "assigns the cidadeempresa as @cidadeempresa" do
        cidadeempresa = Cidadeempresa.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Cidadeempresa.any_instance.stub(:save).and_return(false)
        put :update, {:id => cidadeempresa.to_param, :cidadeempresa => { "nomecidade" => "invalid value" }}, valid_session
        assigns(:cidadeempresa).should eq(cidadeempresa)
      end

      it "re-renders the 'edit' template" do
        cidadeempresa = Cidadeempresa.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Cidadeempresa.any_instance.stub(:save).and_return(false)
        put :update, {:id => cidadeempresa.to_param, :cidadeempresa => { "nomecidade" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested cidadeempresa" do
      cidadeempresa = Cidadeempresa.create! valid_attributes
      expect {
        delete :destroy, {:id => cidadeempresa.to_param}, valid_session
      }.to change(Cidadeempresa, :count).by(-1)
    end

    it "redirects to the cidadeempresas list" do
      cidadeempresa = Cidadeempresa.create! valid_attributes
      delete :destroy, {:id => cidadeempresa.to_param}, valid_session
      response.should redirect_to(cidadeempresas_url)
    end
  end

end
