require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LocalidadelinhasController do

  # This should return the minimal set of attributes required to create a valid
  # Localidadelinha. As you add validations to Localidadelinha, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "nomelocalidade" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LocalidadelinhasController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all localidadelinhas as @localidadelinhas" do
      localidadelinha = Localidadelinha.create! valid_attributes
      get :index, {}, valid_session
      assigns(:localidadelinhas).should eq([localidadelinha])
    end
  end

  describe "GET show" do
    it "assigns the requested localidadelinha as @localidadelinha" do
      localidadelinha = Localidadelinha.create! valid_attributes
      get :show, {:id => localidadelinha.to_param}, valid_session
      assigns(:localidadelinha).should eq(localidadelinha)
    end
  end

  describe "GET new" do
    it "assigns a new localidadelinha as @localidadelinha" do
      get :new, {}, valid_session
      assigns(:localidadelinha).should be_a_new(Localidadelinha)
    end
  end

  describe "GET edit" do
    it "assigns the requested localidadelinha as @localidadelinha" do
      localidadelinha = Localidadelinha.create! valid_attributes
      get :edit, {:id => localidadelinha.to_param}, valid_session
      assigns(:localidadelinha).should eq(localidadelinha)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Localidadelinha" do
        expect {
          post :create, {:localidadelinha => valid_attributes}, valid_session
        }.to change(Localidadelinha, :count).by(1)
      end

      it "assigns a newly created localidadelinha as @localidadelinha" do
        post :create, {:localidadelinha => valid_attributes}, valid_session
        assigns(:localidadelinha).should be_a(Localidadelinha)
        assigns(:localidadelinha).should be_persisted
      end

      it "redirects to the created localidadelinha" do
        post :create, {:localidadelinha => valid_attributes}, valid_session
        response.should redirect_to(Localidadelinha.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved localidadelinha as @localidadelinha" do
        # Trigger the behavior that occurs when invalid params are submitted
        Localidadelinha.any_instance.stub(:save).and_return(false)
        post :create, {:localidadelinha => { "nomelocalidade" => "invalid value" }}, valid_session
        assigns(:localidadelinha).should be_a_new(Localidadelinha)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Localidadelinha.any_instance.stub(:save).and_return(false)
        post :create, {:localidadelinha => { "nomelocalidade" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested localidadelinha" do
        localidadelinha = Localidadelinha.create! valid_attributes
        # Assuming there are no other localidadelinhas in the database, this
        # specifies that the Localidadelinha created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Localidadelinha.any_instance.should_receive(:update_attributes).with({ "nomelocalidade" => "MyString" })
        put :update, {:id => localidadelinha.to_param, :localidadelinha => { "nomelocalidade" => "MyString" }}, valid_session
      end

      it "assigns the requested localidadelinha as @localidadelinha" do
        localidadelinha = Localidadelinha.create! valid_attributes
        put :update, {:id => localidadelinha.to_param, :localidadelinha => valid_attributes}, valid_session
        assigns(:localidadelinha).should eq(localidadelinha)
      end

      it "redirects to the localidadelinha" do
        localidadelinha = Localidadelinha.create! valid_attributes
        put :update, {:id => localidadelinha.to_param, :localidadelinha => valid_attributes}, valid_session
        response.should redirect_to(localidadelinha)
      end
    end

    describe "with invalid params" do
      it "assigns the localidadelinha as @localidadelinha" do
        localidadelinha = Localidadelinha.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Localidadelinha.any_instance.stub(:save).and_return(false)
        put :update, {:id => localidadelinha.to_param, :localidadelinha => { "nomelocalidade" => "invalid value" }}, valid_session
        assigns(:localidadelinha).should eq(localidadelinha)
      end

      it "re-renders the 'edit' template" do
        localidadelinha = Localidadelinha.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Localidadelinha.any_instance.stub(:save).and_return(false)
        put :update, {:id => localidadelinha.to_param, :localidadelinha => { "nomelocalidade" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested localidadelinha" do
      localidadelinha = Localidadelinha.create! valid_attributes
      expect {
        delete :destroy, {:id => localidadelinha.to_param}, valid_session
      }.to change(Localidadelinha, :count).by(-1)
    end

    it "redirects to the localidadelinhas list" do
      localidadelinha = Localidadelinha.create! valid_attributes
      delete :destroy, {:id => localidadelinha.to_param}, valid_session
      response.should redirect_to(localidadelinhas_url)
    end
  end

end
