require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe VeiculolinhasController do

  # This should return the minimal set of attributes required to create a valid
  # Veiculolinha. As you add validations to Veiculolinha, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "veiculo" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # VeiculolinhasController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all veiculolinhas as @veiculolinhas" do
      veiculolinha = Veiculolinha.create! valid_attributes
      get :index, {}, valid_session
      assigns(:veiculolinhas).should eq([veiculolinha])
    end
  end

  describe "GET show" do
    it "assigns the requested veiculolinha as @veiculolinha" do
      veiculolinha = Veiculolinha.create! valid_attributes
      get :show, {:id => veiculolinha.to_param}, valid_session
      assigns(:veiculolinha).should eq(veiculolinha)
    end
  end

  describe "GET new" do
    it "assigns a new veiculolinha as @veiculolinha" do
      get :new, {}, valid_session
      assigns(:veiculolinha).should be_a_new(Veiculolinha)
    end
  end

  describe "GET edit" do
    it "assigns the requested veiculolinha as @veiculolinha" do
      veiculolinha = Veiculolinha.create! valid_attributes
      get :edit, {:id => veiculolinha.to_param}, valid_session
      assigns(:veiculolinha).should eq(veiculolinha)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Veiculolinha" do
        expect {
          post :create, {:veiculolinha => valid_attributes}, valid_session
        }.to change(Veiculolinha, :count).by(1)
      end

      it "assigns a newly created veiculolinha as @veiculolinha" do
        post :create, {:veiculolinha => valid_attributes}, valid_session
        assigns(:veiculolinha).should be_a(Veiculolinha)
        assigns(:veiculolinha).should be_persisted
      end

      it "redirects to the created veiculolinha" do
        post :create, {:veiculolinha => valid_attributes}, valid_session
        response.should redirect_to(Veiculolinha.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved veiculolinha as @veiculolinha" do
        # Trigger the behavior that occurs when invalid params are submitted
        Veiculolinha.any_instance.stub(:save).and_return(false)
        post :create, {:veiculolinha => { "veiculo" => "invalid value" }}, valid_session
        assigns(:veiculolinha).should be_a_new(Veiculolinha)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Veiculolinha.any_instance.stub(:save).and_return(false)
        post :create, {:veiculolinha => { "veiculo" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested veiculolinha" do
        veiculolinha = Veiculolinha.create! valid_attributes
        # Assuming there are no other veiculolinhas in the database, this
        # specifies that the Veiculolinha created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Veiculolinha.any_instance.should_receive(:update_attributes).with({ "veiculo" => "" })
        put :update, {:id => veiculolinha.to_param, :veiculolinha => { "veiculo" => "" }}, valid_session
      end

      it "assigns the requested veiculolinha as @veiculolinha" do
        veiculolinha = Veiculolinha.create! valid_attributes
        put :update, {:id => veiculolinha.to_param, :veiculolinha => valid_attributes}, valid_session
        assigns(:veiculolinha).should eq(veiculolinha)
      end

      it "redirects to the veiculolinha" do
        veiculolinha = Veiculolinha.create! valid_attributes
        put :update, {:id => veiculolinha.to_param, :veiculolinha => valid_attributes}, valid_session
        response.should redirect_to(veiculolinha)
      end
    end

    describe "with invalid params" do
      it "assigns the veiculolinha as @veiculolinha" do
        veiculolinha = Veiculolinha.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Veiculolinha.any_instance.stub(:save).and_return(false)
        put :update, {:id => veiculolinha.to_param, :veiculolinha => { "veiculo" => "invalid value" }}, valid_session
        assigns(:veiculolinha).should eq(veiculolinha)
      end

      it "re-renders the 'edit' template" do
        veiculolinha = Veiculolinha.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Veiculolinha.any_instance.stub(:save).and_return(false)
        put :update, {:id => veiculolinha.to_param, :veiculolinha => { "veiculo" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested veiculolinha" do
      veiculolinha = Veiculolinha.create! valid_attributes
      expect {
        delete :destroy, {:id => veiculolinha.to_param}, valid_session
      }.to change(Veiculolinha, :count).by(-1)
    end

    it "redirects to the veiculolinhas list" do
      veiculolinha = Veiculolinha.create! valid_attributes
      delete :destroy, {:id => veiculolinha.to_param}, valid_session
      response.should redirect_to(veiculolinhas_url)
    end
  end

end
